### ISSUE TITLE
Error on Migration 

### ISSUE THREAD

**Issue by annagreen-juicymedia** [magento/data-migration-tool#383] opened 2017-10-06 14:09 UTC
Hi,

I've set the migration going on my Magento 2.2.0 store with the 2.2.0 version of the module installed but it gets past "sales_flat_order_item" and then stops and gives this error "Notice: Array to string conversion in /vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php on line 169" .

Can anyone help with this please?

**Comment by victor-v-rad** [comment] 2017-10-09 06:08
Perhaps $bind is multi-dimensional array
It would be good if you put var_dump($bind) and var_dump($insertSql) right before [$statement](https://github.com/magento/data-migration-tool/blob/master/src/Migration/ResourceModel/Adapter/Mysql.php#L168) and show here. If it is not tool big.
Also you can run migration with `-vvv` param to see backtrace

**Comment by victor-v-rad** [comment] 2017-10-10 10:44
@annagreen-juicymedia 
try this fix https://github.com/magento-panda/data-migration-tool/commit/5fc6ff3c5c89aea88e8843c55fdafc9cf3bd6f3b

**Comment by annagreen-juicymedia** [comment] 2017-10-10 11:23
Thanks for the link! Will try this now.

**Comment by victor-v-rad** [comment] 2017-10-11 09:44
@annagreen-juicymedia 

Here is the fix for `Notice: Array to string conversion` https://github.com/magento-panda/data-migration-tool/commit/1d3226c833be529c288ffa951658577669855541
It will be included into the next release by default

**Comment by RickObid** [comment] 2017-10-12 14:45
i have the same problem and i got it fix by 1d3226c (thank you Victor), now i past the 84% in [stage: data migration][step: Map Step] and other error showing up in 97%.
`[2017-10-12 14:05:40][INFO][mode: data][stage: data migration][step: Map Step]: started
97% [===========================>] Remaining Time: 30 secs

  [Exception]
  Notice: unserialize(): Error at offset 156 of 227 bytes in /home/titest/public_html/vendor/magento/data-migration-tool/src/Migration/Handler/SerializeToJson.php on line 37
`

i did try twice and my data is 5000 product with 100,000 orders.

**Comment by victor-v-rad** [comment] 2017-10-13 09:18
It would be best to report it as a separate issue. The issue is that some serialized data is broken. Please run the tool with -vvv option to see which table causes the issue. After you can add ignoreBrokenData option to that table like
```
            <transform>
                <field>sales_flat_shipment.packages</field>
                <handler class="\Migration\Handler\SerializeToJson">
                    <param name="ignoreBrokenData" value="true"/>
                </handler>
            </transform>
```

**Comment by RickObid** [comment] 2017-10-13 15:59
Its work! (-vvv) help me a lot as will show the status of each table.
i run
( php bin/magento migrate:data -r -vvv /home/XXXXX/public_html/vendor/magento/data-migration tool/etc/opensource-to-opensource/1.9.3.0/config.xml.dist)
 i see it stop at widget_instance table. 

and i ignore it in the map (map.xml.dist)

>              <ignore>
>                 <document>widget</document>
>             </ignore>
>              <ignore>
>                 <document>widget_*</document>
>             </ignore>

Now  Migration completed for me for the first time after one week work :)

thank you Victor

**Closed** 2017-11-10 06:02 UTC
