### ISSUE TITLE
Magento 2.1.2 upgrade issue

### ISSUE THREAD

**Issue by Roque64** [magento/data-migration-tool#171] opened 2016-10-17 12:06 UTC
Hello there,

I was trying to Upgrade from Magento 2.1.0 to Magento 2.1.2 through the System Upgrade, I'm using PHP7.0.7, and I got this error:

Parse error: syntax error, unexpected '.' in /home/portugue/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93
 
After using a backup to restore the site I tried the upgrade using the command line and I got the same error.
I followed the guide steps: http://devdocs.magento.com/guides/v2.1/comp-mgr/cli/cli-upgrade.html
And I even deleted 
/var/cache 
/var/page_cache 
/var/generation

Can you please help me on that? 
Thanks

**Comment by victor-v-rad** [comment] 2016-10-18 10:09
Are you sure the issue is up to Data Migration Tool?

**Comment by Roque64** [comment] 2016-10-18 13:41
Hi, I was still working on the Magento configuration. The only thing I've done previously was to install Porto Theme. No other components were installed. I can't see what else could be.
Thanks

**Comment by victor-v-rad** [comment] 2016-10-19 07:48
Ok. I'm closing the issue. Fell free to reopen it or create new one if face the problem related to the tool

**Closed by victor-v-rad** 2016-10-19 07:48 UTC
Labels: question
