### ISSUE TITLE
Bundle Product price is required when dynamic price enabled after data migration from magento1 to magento2

### ISSUE THREAD

**Issue by magentoguyssageone** [magento/data-migration-tool#661] opened 2019-02-25 12:39 UTC
### Preconditions (*)

1. Install Fresh Magento version 2.2.7
2. Install Data Migration tool 
3. Complete Data Migration from Magento1(Magento versie 1.9.3.2) to Magento2

### Steps to reproduce (*)

1. After Complete Data migration go to Magento2 admin and Edit any migrated bundle product
2. Bunle Product has Dynamic Price set to Yes : http://prntscr.com/mptl6t
3. Try to Save Bundle Product but unable to save becuase Price is Required field for bundle product for my magento2 website. : http://prntscr.com/mptlxk

### Expected result (*)

1. Bundle Product price should not required as Dynamic Price is Yes
2. Bundle Product should Save Successfully without required price error.

### Actual result (*)

1.  Try to Save Bundle Product but unable to save becuase Price is Required field for bundle product for my magento2 website. : http://prntscr.com/mptlxk but it should not required and price filed should disabled.

**Comment by victor-v-rad** [comment] 2019-03-04 14:39
Hi @magentoguyssageone 

Internal ticket MAGETWO-98531 was created to fix this issue

**Comment by VDCProjects** [comment] 2019-03-19 12:00
Hi,

any update about this issue?

Thanks

**Comment by MagentoGuysProjects** [comment] 2019-05-01 12:43
Hi,

its very long time and no update.
can you please update about the status of this issue ?

Thanks

**Comment by victor-v-rad** [comment] 2019-05-01 15:37
Hi,

The ticket is in queue for development, but the tool is open source and you can make a great contribution for all Magento community.

**Comment by MagentoGuysProjects** [comment] 2019-06-03 06:44
Hi,

Any progress about this issue ?

**Comment by victor-v-rad** [comment] 2019-09-25 22:40
Hi @MagentoGuysProjects @VDCProjects @magentoguyssageone 
I did not able to reproduce the issue on the latest Magento 2.3.2 and the tool 2.3.2. 
Probably it was fixed in #574 It looks very similar.

**Closed as completed** 2019-09-25 22:40 UTC
Labels: bug

**Comment by ityetti** [comment] 2020-01-06 15:03
@victor-v-rad I have a similar problem, and I'm looking for a solution to fix it without starting a full data migration again.
