### ISSUE TITLE
1.9.2.2 -> 2.0.1 Admin Login fails after migrate:settings

### ISSUE THREAD

**Issue by MikeDevs** [magento/data-migration-tool#58] opened 2016-01-28 17:00 UTC
I've done the following steps twice:

- Clean/working 1.9.2.2 store with no extensions, ~100 products, ~3,000 customers, ~10,000 orders
- Install Magento 2.0.1
- Confirm 2.0.1 is working front/back
- Install latest data-migration-tool with composer
- Run bin/magento migrate:settings (config)
- Process completes, logs look good
- Go to admin login, enter correct username/password for the new store. The login appears successful but the browser is returned to the login page. 

Notes: 
- Logging is enabled, nothing in the logs suggesting an issue.
- Nothing in Apache error logs. 
- Nothing in the browser console.
- Firebug Network Activity suggests a successful login with a cookie set as expected.
- The relevant user row in table admin_user increments 'lognum' after each login, and there are 0 'failures_num'.
- I can register new accounts and login via the front end. 
- After migrate:settings I can successfully migrate:data and everything appears normally on the front end. 

I've tried reindexing, clearing the cache, deleting browser cookies, trying different browsers that have never visited the store, etc. Having now done the entire process twice my only guess is a settings on the 1.9.2.2 install screws up the admin login. I've tried adjusting the cookie settings (the only thing I could think of that could screw this up) via SQL to no avail. 

Has anyone run into this before? Is this an issue specific to 2.0.1 perhaps (not sure if it is supported)?

**Comment by MikeDevs** [comment] 2016-01-28 19:05
Just an update- this does not seem to be an issue with the data-migration-tool but likely a result of some setting in the 1.9.2.2 store that results in the above issue. 

After stating with a clean 2.0.1 store and running migrate:data only, everything works and the data is brought over. Additionally, in testing, migrate:delta is also working. We manually updated the important settings/config and so far all seems to be working as expected.

**Comment by rkhoury82** [comment] 2016-01-28 21:56
@MikeDevs I had that same issue, the migrate:settings takes EVERYTHING from CORE_CONFIG_DATA  table and i found that some of the old module settings created conflicts with Magento2. Not sure how that could be fixed, but something people should be aware of.

**Comment by victor-v-rad** [comment] 2016-05-05 13:23
Hi @MikeDevs @rkhoury82 
Though I have not had such issue with admin login I would strongly recommend not to skip entire setting mode but comment only "Settings Step" in your config.xml . Since as you can see there is "Stores Step" inside the "settings" mode, which must be executed.

**Comment by lkoptsio** [comment] 2016-08-03 21:47
Running migration tool creates file var/migration-tool-progress.lock After removing it - admin login become functional again.

**Comment by victor-v-rad** [comment] 2016-09-13 12:28
Seems the issue is fixed. Hence closing it

**Closed by victor-v-rad** 2016-09-13 12:28 UTC
