### ISSUE TITLE
Magento 1.9.3.6 To Magento 2.2.0

### ISSUE THREAD

**Issue by AbdulKadir-Agoliya** [magento/data-migration-tool#379] opened 2017-10-05 09:34 UTC
I am attempting to migrate from 1.9.3.6 to 2.2.0 Opensource to opensource using the data migration tool.
using command : php bin/magento migrate:data /path-to/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.6/config.xml

Expected result
1. Migration error shoud be display

Actual result

php bin/magento migrate:data --reset /public_html/mag2/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.6/config.xml
Reset the current position of migration to start from the beginning

[2017-10-05 09:27:32][INFO][mode: data][stage: integrity check][step: Data Integrity Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:32][INFO][mode: data][stage: integrity check][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:32][INFO][mode: data][stage: integrity check][step: Customer Attributes Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:32][INFO][mode: data][stage: integrity check][step: Map Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:34][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:34][INFO][mode: data][stage: integrity check][step: Log Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:34][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:34][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:34][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:34][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:34][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:34][INFO][mode: data][stage: setup triggers][step: Stage]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:35][INFO][mode: data][stage: data migration][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:36][INFO][mode: data][stage: volume check][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:36][INFO][mode: data][stage: data migration][step: Customer Attributes Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:59][INFO][mode: data][stage: volume check][step: Customer Attributes Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 09:27:59][INFO][mode: data][stage: data migration][step: Map Step]: started
38% [==========>-----------------] Remaining Time: 3 mins
                                                                                               
  [PDOException]                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'  
                                                                                               

migrate:data [-r|--reset] [-a|--auto] [--] <config>

**Comment by yogeshsyscraft** [comment] 2017-10-05 10:05
Please Go to `Var/migration.log`  and check the main error .

**Comment by victor-v-rad** [comment] 2017-10-05 10:06
run with `-vvv` to see what table causes the error

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-05 10:22
[2017-10-05 10:19:29][DEBUG][mode: data][stage: data migration][step: Map Step][table: customer_group]: migrating
28% [========>-------------------] Remaining Time: < 1 sec
                                                                                               
  [PDOException]                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'  
                                                                                               

Exception trace:
 () at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php:169
 PDOStatement->execute() at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php:169
 Migration\ResourceModel\Adapter\Mysql->insertMultiple() at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php:137
 Migration\ResourceModel\Adapter\Mysql->insertRecords() at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Destination.php:46
 Migration\ResourceModel\Destination->saveRecords() at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/Step/Map/Data.php:175
 Migration\Step\Map\Data->perform() at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/Mode/AbstractMode.php:73
 Migration\Mode\AbstractMode->runStage() at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:122
 Migration\Mode\Data->runData() at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/Mode/Data.php:69
 Migration\Mode\Data->run() at /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/Console/MigrateDataCommand.php:51
 Migration\Console\MigrateDataCommand->execute() at /home/mazelivingco/public_html/mag2/vendor/symfony/console/Command/Command.php:266
 Symfony\Component\Console\Command\Command->run() at /home/mazelivingco/public_html/mag2/vendor/symfony/console/Application.php:875
 Symfony\Component\Console\Application->doRunCommand() at /home/mazelivingco/public_html/mag2/vendor/symfony/console/Application.php:204
 Symfony\Component\Console\Application->doRun() at /home/mazelivingco/public_html/mag2/vendor/magento/framework/Console/Cli.php:104
 Magento\Framework\Console\Cli->doRun() at /home/mazelivingco/public_html/mag2/vendor/symfony/console/Application.php:122
 Symfony\Component\Console\Application->run() at /home/mazelivingco/public_html/mag2/bin/magento:23

migrate:data [-r|--reset] [-a|--auto] [--] <config>


I cant getting what to do here

**Comment by victor-v-rad** [comment] 2017-10-05 11:13
could you show all the data from the `customer_group` table?

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-05 11:45
This Is M1  Table
https://www.awesomescreenshot.com/image/2867969/279d19f21945030a59634af37d515d51

This Is M2  Table
https://www.awesomescreenshot.com/image/2867974/969f1a27b4007dff66dc3396abd31d41

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-05 11:59
When error comes in migration and then after i saw table customer_group

and i see there is only one record
https://www.awesomescreenshot.com/image/2868020/3687c556643d32ac57fcb9d08bb8a302

**Comment by victor-v-rad** [comment] 2017-10-05 12:12
Did you set `<direct_document_copy>`  1 in your config.xml file?

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-05 12:44
Just Error Message change but result same
in customer_group table

[2017-10-05 12:19:25][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 12:19:25][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 12:19:25][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 12:19:25][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 12:19:25][INFO][mode: data][stage: setup triggers][step: Stage]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 12:19:25][INFO][mode: data][stage: data migration][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 12:19:26][INFO][mode: data][stage: volume check][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 12:19:27][INFO][mode: data][stage: data migration][step: Customer Attributes Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 12:19:51][INFO][mode: data][stage: volume check][step: Customer Attributes Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-05 12:19:51][INFO][mode: data][stage: data migration][step: Map Step]: started
38% [==========>-----------------] Remaining Time: 3 mins
                                                                                               
  [PDOException]                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'  
                                                                                               

migrate:data [-r|--reset] [-a|--auto] [--] <config>

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-05 12:56
result same in customer_group table 
https://www.awesomescreenshot.com/image/2868020/3687c556643d32ac57fcb9d08bb8a302

[2017-10-05 12:19:51][INFO][mode: data][stage: data migration][step: Map Step]: started
38% [==========>-----------------] Remaining Time: 3 mins

[PDOException]
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'

Now what to do?

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-06 09:45
Can anyone help here  Migrating from magento1.9.3.6 to magento2.2.0

I got this error 

Array to string conversion in /var/www/html/magento220/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.p  
  hp on line 169
[3:12:39 PM] Jigar Patel: [2017-10-06 09:33:42][INFO][mode: data][stage: integrity check][step: Data Integrity Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-06 09:33:50][INFO][mode: data][stage: integrity check][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-06 09:33:50][INFO][mode: data][stage: integrity check][step: Customer Attributes Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-06 09:33:50][INFO][mode: data][stage: integrity check][step: Map Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-06 09:33:58][INFO][mode: data][stage: integrity check][step: Url Rewrite Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-06 09:33:58][INFO][mode: data][stage: integrity check][step: Log Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-06 09:33:59][INFO][mode: data][stage: integrity check][step: Ratings Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-06 09:33:59][INFO][mode: data][stage: integrity check][step: ConfigurablePrices step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-06 09:33:59][INFO][mode: data][stage: integrity check][step: OrderGrids Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-06 09:33:59][INFO][mode: data][stage: integrity check][step: Tier Price Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-06 09:33:59][INFO][mode: data][stage: integrity check][step: SalesIncrement Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-06 09:33:59][INFO][mode: data][stage: setup triggers][step: Stage]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-06 09:34:41][INFO][mode: data][stage: data migration][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-06 09:34:52][INFO][mode: data][stage: volume check][step: EAV Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-06 09:34:53][INFO][mode: data][stage: data migration][step: Customer Attributes Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-06 09:35:09][INFO][mode: data][stage: volume check][step: Customer Attributes Step]: started
100% [============================] Remaining Time: < 1 sec
[2017-10-06 09:35:09][INFO][mode: data][stage: data migration][step: Map Step]: started
77% [=====================>------] Remaining Time: 1 min
                                                                                                                                                 
  [Exception]                                                                                                                                    
  Notice: Array to string conversion in /var/www/html/magento220/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.p  
  hp on line 169                                                                                                                                 
                                                                                                                                                 

migrate:data [-r|--reset] [-a|--auto] [--] <config>


Please help me here its urgent and i have to finish it today

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-06 10:30
Hello victor 
   Many thanks for your Quick Response.and i got again issue can you please suggest me what to do next here?

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-06 12:39
Hello Victor,

 i have removed one module's column from M1's customer_group table and now that error gone

and now same error comes from sales_flat_order_item   

so i think when 
migrate mode data  , its not ignoring field  

so please give me solution for that  
error come on 
data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php on line 169 $statement->execute($bind);
function name insertMultiple($documentName, $records)

**Comment by wejobes** [comment] 2017-10-06 19:35
I am having the same issue as well with the customer_group table.  I also have modules that have added columns to this table, but have added "ignore" entries for them in the map file.

**Comment by wejobes** [comment] 2017-10-06 20:00
I added some debugging to this.  It looks like the Mysql::insertMultiple() method is being called twice with the same data for some reason:

[2017-10-06 19:53:36][DEBUG][mode: data][stage: data migration][step: Map Step][table: customer_group]: migrating
7% [==>-------------------------] Remaining Time: < 1 sec
 INSERT INTO customer_group (`customer_group_id`,`customer_group_code`,`tax_class_id`) VALUES (?,?,?) 
Array
(
    [0] => (?,?,?)
)
Array
(
    [0] => 0
    [1] => NOT LOGGED IN
    [2] => 3
)
15% [====>-----------------------] Remaining Time: < 1 sec
 INSERT INTO customer_group (`customer_group_id`,`customer_group_code`,`tax_class_id`) VALUES (?,?,?) 
Array
(
    [0] => (?,?,?)
)
Array
(
    [0] => 0
    [1] => NOT LOGGED IN
    [2] => 3
)

**Comment by wejobes** [comment] 2017-10-06 20:29
Okay, looks like this an issue with the `bulk_size` option.  I had it set to `0` when I was getting the error.  Digging into the code, I was seeing how the page size is being managed by this value.  If it is `0` then the tool is supposed to find the best size for that table.  Because I was getting the same row of data looped, I decided to change this value to see what would happen, so I changed it to `5`.  The migration tool started to run again with no issue and is currently running.

Questions that remain:

- Why did the Migration\ResourceModel\Source::getRecords() return the same record?
- What calculation is failing in Migration\ResourceModel\Source::getPageSize() which seems to be linked to this issue?
- Are custom columns that have been marked as ignored in the map.xml file part of the cause as well?

If I find anything, I will post in here.

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-07 05:23
Yes i also print query and i see query fire two times 
This is My M1 Customer_group table Data

customer_group_id     customer_group_code    tax_class_id      bakerloo_payment_methods
	0			    NOT LOGGED IN		3		        Null
	1			   General					3		        Null
	2			   Wholesale				3		        Null
	3			   Retailer					3		        Null
	4			   FOB					3		        Null
	5			   Ex Whs					3		        Null
	6			  Container				3		        Null



see 
INSERT INTO customer_group (`customer_group_id`,`customer_group_code`,`tax_class_id`) VALUES (?,?,?)
PDOStatement Object
(
    [queryString] => INSERT INTO customer_group (`customer_group_id`,`customer_group_code`,`tax_class_id`) VALUES (?,?,?)
)
Array
(
    [0] => 0
    [1] => NOT LOGGED IN
    [2] => 3
)
INSERT INTO customer_group (`customer_group_id`,`customer_group_code`,`tax_class_id`) VALUES (?,?,?)
PDOStatement Object
(
    [queryString] => INSERT INTO customer_group (`customer_group_id`,`customer_group_code`,`tax_class_id`) VALUES (?,?,?)
)
Array
(
    [0] => 0
    [1] => NOT LOGGED IN
    [2] => 3
)
  [PDOException]                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'


Is Anybody there to answer This problem ?

**Comment by wejobes** [comment] 2017-10-07 05:36
Look at my response above. I was able to get the entire migration to run by setting the bulk_size option to something to other than 0. I stopped the operation at one point and changed it to 250. All my site data has been transferred.

There is a big, but setting the bulk_size seems to be a work around

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-07 06:41
I Removed extra column from M1 database's customer_group table 

and now error is 

Notice: Array to string conversion in /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php on line 169

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-07 06:51
Thanks wejobes for your Quick Response and i have set bulk_size to 250 as you said and re-run migration  previous error solve but i got this error on same line
Notice: Array to string conversion in /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php on line 169

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-07 06:57
wejobes Do you have any idea related to this issue ?

**Comment by wejobes** [comment] 2017-10-09 13:58
For the `Notice: Array to string conversion in /home/mazelivingco/public_html/mag2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php on line 169` issue, you would need to be running in verbose mode so you can debug the issue more.

Once I set my bulk_size I didn't have anymore issues.

**Comment by victor-v-rad** [comment] 2017-10-11 09:44
@wejobes 
Here is the fix for `Notice: Array to string conversion` https://github.com/magento-panda/data-migration-tool/commit/1d3226c833be529c288ffa951658577669855541
It will be included into the next release by default

**Comment by victor-v-rad** [comment] 2017-10-11 11:32
@AbdulKadir-Agoliya @wejobes 
I guess I know where the error `SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY' ` comes from. 
It happens when `<bulk_size>1</bulk_size>`

**Comment by grablor** [comment] 2017-10-29 19:51
I am migrating from 1.9.1.1 to 2.2.0 and I was also getting `SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'` error. I followed @wejobes solution and changed bulk_size from 0 to 250 <bulk_size>250</bulk_size> and it worked like charm.
Thanks @wejobes

**Closed** 2018-05-03 10:05 UTC
