### ISSUE TITLE
After running migration it is not possible to checkout on stores Id > 1

### ISSUE THREAD

**Issue by redboxmarcins** [magento/data-migration-tool#77] opened 2016-04-08 12:19 UTC
It is related to https://github.com/magento/magento2/issues/3066 

Data migration tool should recreate meta sequence tables

More/less what observer on store_add does:

```php
foreach ($storeIds as $storeId) {
            foreach ($entityPool as $entityType) {
                $this->sequenceBuilder->setPrefix($storeId)
                    ->setSuffix($this->sequenceConfig->get('suffix'))
                    ->setStartValue($this->sequenceConfig->get('startValue'))
                    ->setStoreId($storeId)
                    ->setStep($this->sequenceConfig->get('step'))
                    ->setWarningValue($this->sequenceConfig->get('warningValue'))
                    ->setMaxValue($this->sequenceConfig->get('maxValue'))
                    ->setEntityType($entityType)
                    ->create();
                }
        }
```

**Comment by ilol** [comment] 2016-04-28 16:30
Thank you @redboxmarcins, discussing this internally

**Comment by victor-v-rad** [comment] 2016-05-05 06:48
Hi,
An internal issue was created to investigate this issue

**Comment by ilol** [comment] 2016-05-10 14:28
MAGETWO-52506

**Comment by victor-v-rad** [comment] 2016-06-07 14:48
Sorry for late reply. I assume you did not migrate settings before data migration
`php bin/magento migrate:settings`

**Comment by ilol** [comment] 2016-09-12 12:16
Hey!
I am temporary closing this until respond

**Closed by ilol** 2016-09-12 12:16 UTC

**Comment by craigcarnell** [comment] 2017-01-06 11:10
@victor-v-rad @ilol I have this issue, it's a major issue. We are unable to place orders. I did migrate settings and data.

But as you know the data one never completes properly due to the url rewrites issue.

**Comment by dfelton** [comment] 2017-01-06 16:23
@craigcarnell data should complete properly once everything is sitting good. Are you encountering "Duplicates" in the url rewrites or what's your issue?

**Comment by craigcarnell** [comment] 2017-01-09 09:42
@dfelton It's says I have duplicates but I believe the reported issue is not correct. It complains about duplicates however they are for different stores:

https://github.com/magento/data-migration-tool/issues/26
https://github.com/magento/data-migration-tool/issues/81

**Comment by dfelton** [comment] 2017-01-09 17:46
@craigcarnell The output of the console for these [is already grouped](https://github.com/magento/data-migration-tool/blob/master/src/Migration/Step/UrlRewrite/Version11410to2000.php#L562) by `store_id` and `request_path`, so when you see for example:

```
Request path was: cylinder-vacuum-cleaners/swift-cylinder Target path was: catalog/category/view/id/63 Store ID: 4 New request path: cylinder-vacuum-cleaners/swift-cylinder
Request path was: cylinder-vacuum-cleaners/swift-cylinder Target path was: catalog/category/view/id/63 Store ID: 22 New request path: cylinder-vacuum-cleaners/swift-cylinder
```

This means that you have a duplicate of that `request_path` for **both** `store_id` 4, and 22. 

In my case, **all** my duplicates where due to redirects of products, or custom redirects added to the redirect table. I decided to handle this by flat out ignoring these records. Close examination of my own data showed that for every duplicate, one record was the "URL Rewrite" to "/catalog/product/view/id/**someId**" and another was a redirect for the very same product URL. I decided that it was more important to keep the URL **Rewrite** that is used to make the product work in the first place. 

This was accomplished by writing my own class to extend the native Migration class, and revising the [Version11410to2000::collectRedirects()](https://github.com/magento/data-migration-tool/blob/master/src/Migration/Step/UrlRewrite/Version11410to2000.php#L1019) method. 

```php
<?php

namespace Migration\Govmint\Step\UrlRewrite;

class Version11410to2000 extends \Migration\Step\UrlRewrite\Version11410to2000
{

    /**
     * Fulfill temporary table with redirects
     *
     * Modified so that redirects are not inserted if it were to create a
     * duplicate.
     *
     * @param \Migration\ResourceModel\Adapter\Mysql $adapter
     * @return void
     */
    protected function collectRedirects(\Migration\ResourceModel\Adapter\Mysql $adapter)
    {
        $select = $adapter->getSelect();
        $select
            ->from(
                ['r' => $this->source->addDocumentPrefix('enterprise_url_rewrite')],
                [
                    'id' => 'IFNULL(NULL, NULL)',
                    'request_path' => 'r.request_path',
                    'target_path' => 'r.target_path',
                    'is_system' => 'r.is_system',
                    'store_id' => 'r.store_id',
                    'entity_type' => "trim('custom')",
                    'redirect_type' => "trim('0')",
                    'product_id' => "trim('0')",
                    'category_id' => "trim('0')",
                    'cms_page_id' => "trim('0')",
                    'priority' => "trim('2')"
                ])
            ->joinLeft(
                ['m2' => $this->source->addDocumentPrefix($this->tableName)],
                'm2.request_path=r.request_path AND m2.store_id=r.store_id',
                [])
            ->where('m2.request_path IS NULL')
        ;
        $query = $select->where('`r`.`entity_type` = 1')
            ->where('r.request_path <> r.target_path')
            ->insertFromSelect($this->source->addDocumentPrefix($this->tableName));
        $select->getAdapter()->query($query);

        $select = $adapter->getSelect();
        $select
            ->from(
                ['r' => $this->source->addDocumentPrefix('enterprise_url_rewrite_redirect')],
                [
                    'id' => 'IFNULL(NULL, NULL)',
                    'request_path' => 'r.identifier',
                    'target_path' => 'r.target_path',
                    'is_system' => "trim('0')",
                    'store_id' => 'r.store_id',
                    'entity_type' => "trim('custom')",
                    'redirect_type' => "(SELECT CASE r.options WHEN 'RP' THEN 301 WHEN 'R' THEN 302 ELSE 0 END)",
                    'product_id' => "r.product_id",
                    'category_id' => "r.category_id",
                    'cms_page_id' => "trim('0')",
                    'priority' => "trim('1')"
                ])
            ->joinLeft(
                ['m2' => $this->source->addDocumentPrefix($this->tableName)],
                'm2.request_path=r.identifier AND m2.store_id=r.store_id',
                [])
            ->where('m2.request_path IS NULL')
            ->where('r.identifier <> r.target_path')
        ;

        $query = $select->insertFromSelect($this->source->addDocumentPrefix($this->tableName));
        $select->getAdapter()->query($query);
    }

}
```

When comparing this to the original source code, you'll see that I've added a LEFT JOIN on the table which the Migration tool collects **all** records into. And then added a WHERE clause to only select `WHERE m2.request_path IS NULL` (meaning, there isn't already a rewrite with this same request path and store id).

FYI-- My database also had some redirect loops setup (I blame marketing department lol). These were omitted with this line:
```php
            ->where('r.identifier <> r.target_path')
```

For your situation I recommend verifying the logic since I think you are using the [Version11300to2000](https://github.com/magento/data-migration-tool/blob/master/src/Migration/Step/UrlRewrite/Version11300to2000.php) class instead of the [Version11410to2000](https://github.com/magento/data-migration-tool/blob/master/src/Migration/Step/UrlRewrite/Version11410to2000.php) class.

Additionally, in order to use this new PHP class I had to change my XML configuration to reflect this. 

```xml
<step title="Url Rewrite Step">
   <integrity>Migration\Govmint\Step\UrlRewrite\Version11410to2000</integrity>
   <data>Migration\Step\UrlRewrite\Version11410to2000</data>
   <volume>Migration\Step\UrlRewrite\Version11410to2000</volume>
</step>
```

**Comment by craigcarnell** [comment] 2017-01-11 13:38
@dfelton Many thanks for your help on this

I've checked enterprise_url_rewrite and this is what I have for this particular product:

```
url_rewrite_id	request_path	target_path	is_system	guid	identifier	inc	value_id	store_id	entity_type
29552213	cylinder-vacuum-cleaners/swift-cylinder	catalog/category/view/id/63	1	f1a57b1e3de60154020ac03cc3a84105	cylinder-vacuum-cleaners/swift-cylinder	1	58	4	2
```

But in the m2 temp tables there are 4 records?

SELECT `r`.* FROM `url_rewrite_m2eff37bff5d3cbae9d36f1bbc504408f3` AS `r` where request_path = 'cylinder-vacuum-cleaners/swift-cylinder'

```
id	request_path	target_path	is_system	store_id	entity_type	redirect_type	product_id	category_id	cms_page_id	priority
67922	cylinder-vacuum-cleaners/swift-cylinder	catalog/category/view/id/63	1	4	category	0	0	63	0	3
67921	cylinder-vacuum-cleaners/swift-cylinder	catalog/category/view/id/63	1	22	category	0	0	63	0	3
1165	cylinder-vacuum-cleaners/swift-cylinder	catalog/product/view/id/356/category/47	1	4	product	0	356	47	0	4
1167	cylinder-vacuum-cleaners/swift-cylinder	catalog/product/view/id/356/category/47	1	22	product	0	356	47	0	4
```

Which if we group by as you mentioned:
```
id	request_path	target_path	is_system	store_id	entity_type	redirect_type	product_id	category_id	cms_page_id	priority
67922	cylinder-vacuum-cleaners/swift-cylinder	catalog/category/view/id/63	1	4	category	0	0	63	0	3
67921	cylinder-vacuum-cleaners/swift-cylinder	catalog/category/view/id/63	1	22	category	0	0	63	0	3
```

If I now check my enterprise_url_rewrite table for 'catalog/product/view/id/356/category/47':

```
url_rewrite_id	request_path	target_path	is_system	guid	identifier	inc	value_id	store_id	entity_type
60382218	cylinder-vacuum-cleaners/swift-cylinder-686	catalog/product/view/id/356/category/47	0	5828a706d4fbdd962a3c1a170b4d65ca	cylinder-vacuum-cleaners/swift-cylinder-686	1	452	4	1
60385724	cylinder-vacuum-cleaners/swift-cylinder-676	catalog/product/view/id/356/category/47	0	5828a706d4fbdd962a3c1a170b4d65ca	cylinder-vacuum-cleaners/swift-cylinder-676	1	6286	22	1
```

The request_path is unique - 686 and 676 not 'cylinder-vacuum-cleaners/swift-cylinder'

I've checked my settings and I am using Version11410to2000. I will try your code however and hope!

Incidentally, the query:

SELECT `r`.* FROM `url_rewrite_m2eff37bff5d3cbae9d36f1bbc504408f3` AS `r`
 GROUP BY `request_path`,
	  `store_id` HAVING (COUNT(*) > 1)

returns 8150 records.

**Comment by dfelton** [comment] 2017-01-11 15:42
@craigcarnell The migration tool will collect from numerous sources of your M1 EE database. This is why you are only finding one record (per store view) in your `enterprise_url_rewrite` table, but duplicates in the `url_rewrite_m2eff37bff5d3cbae9d36f1bbc504408f3` table.

If you're looking to find the exact records that cause your duplicates, you'll want to start searching in these various tables for the occurrences of the `request_path`, not the `target_path`. 

#### Example:
```sql
SET @storeId = 4;
SET @lookingFor = 'cylinder-vacuum-cleaners/swift-cylinder-686';

SELECT FROM `enterprise_url_rewrite` WHERE `request_path` = @lookingFor AND `store_id` = @storeId;
SELECT FROM `enterprise_url_rewrite_redirect` WHERE `identifier` = @lookingFor AND `store_id` = @storeId;
SELECT FROM `cms_page` INNER JOIN `cms_page_store` ON `cms_page_store`.`page_id` = `cms_page`.`page_id` AND `cms_page_store`.`store_id` = @storeId WHERE `cms_page`.`identifier` = @lookingFor;
```

In order to not result in a duplicate, there should only be 1 result from all three of the above selects (not one from each, but 1 result total).

**Comment by craigcarnell** [comment] 2017-01-11 15:46
@dfelton I tried your code and it still errors for me I'm afraid:

```
[2017-01-11 15:45:16][INFO][mode: data][stage: data migration][step: Url Rewrite Step]: started
my collectRedirects

30% [========>-------------------] Remaining Time: 53 secs
[2017-01-11 15:45:56][INFO][mode: data][stage: data migration][step: Url Rewrite Step]: Duplicate resolved. Request path was: upright-vacuum-cleaners/swift-upright Target path was: catalog/category/view/id/54 Store ID: 22 New request path: upright-vacuum-cleaners/swift-upright
[2017-01-11 15:45:56][INFO][mode: data][stage: data migration][step: Url Rewrite Step]: Duplicate resolved. Request path was: upright-vacuum-cleaners/swift-upright Target path was: catalog/category/view/id/54 Store ID: 4 New request path: upright-vacuum-cleaners/swift-upright
[2017-01-11 15:45:56][INFO][mode: data][stage: data migration][step: Url Rewrite Step]: Duplicate resolved. Request path was: upright-vacuum-cleaners/turboforce-upright Target path was: catalog/category/view/id/55 Store ID: 4 New request path: upright-vacuum-cleaners/turboforce-upright
[2017-01-11 15:45:56][INFO][mode: data][stage: data migration][step: Url Rewrite Step]: Duplicate resolved. Request path was: upright-vacuum-cleaners/turboforce-upright Target path was: catalog/category/view/id/55 Store ID: 22 New request path: upright-vacuum-cleaners/turboforce-upright
[2017-01-11 15:45:56][INFO][mode: data][stage: data migration][step: Url Rewrite Step]: Duplicate resolved. Request path was: upright-vacuum-cleaners/essentials-upright Target path was: catalog/category/view/id/56 Store ID: 22 New request path: upright-vacuum-cleaners/essentials-upright
[2017-01-11 15:45:56][INFO][mode: data][stage: data migration][step: Url Rewrite Step]: Duplicate resolved. Request path was: upright-vacuum-cleaners/essentials-upright Target path was: catalog/category/view/id/56 Store ID: 4 New request path: upright-vacuum-cleaners/essentials-upright
[2017-01-11 15:45:56][INFO][mode: data][stage: data migration][step: Url Rewrite Step]: Duplicate resolved. Request path was: cylinder-vacuum-cleaners/essentials-cylinder Target path was: catalog/category/view/id/62 Store ID: 4 New request path: cylinder-vacuum-cleaners/essentials-cylinder
[2017-01-11 15:45:56][INFO][mode: data][stage: data migration][step: Url Rewrite Step]: Duplicate resolved. Request path was: cylinder-vacuum-cleaners/essentials-cylinder Target path was: catalog/category/view/id/62 Store ID: 22 New request path: cylinder-vacuum-cleaners/essentials-cylinder
[2017-01-11 15:45:56][INFO][mode: data][stage: data migration][step: Url Rewrite Step]: Duplicate resolved. Request path was: cylinder-vacuum-cleaners/swift-cylinder Target path was: catalog/category/view/id/63 Store ID: 22 New request path: cylinder-vacuum-cleaners/swift-cylinder
[2017-01-11 15:45:56][INFO][mode: data][stage: data migration][step: Url Rewrite Step]: Duplicate resolved. Request path was: cylinder-vacuum-cleaners/swift-cylinder Target path was: catalog/category/view/id/63 Store ID: 4 New request path: cylinder-vacuum-cleaners/swift-cylinder
[2017-01-11 15:45:56][INFO][mode: data][stage: data migration][step: Url Rewrite Step]: Duplicate resolved. Request path was: cylinder-vacuum-cleaners/white-cylinder Target path was: catalog/category/view/id/159 Store ID: 4 New request path: cylinder-vacuum-cleaners/white-cylinder
[2017-01-11 15:45:56][INFO][mode: data][stage: data migration][step: Url Rewrite Step]: Duplicate resolved. Request path was: cylinder-vacuum-cleaners/white-cylinder Target path was: catalog/category/view/id/159 Store ID: 22 New request path: cylinder-vacuum-cleaners/white-cylinder

                                                                                                                                                                
  [PDOException]                                                                                                                                                
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'upright-vacuum-cleaners/swift-upright-22' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID'
```

**Comment by craigcarnell** [comment] 2017-01-11 15:50
@dfelton 

```
SET @storeId = 22;
SET @lookingFor = 'upright-vacuum-cleaners/swift-upright-22';

SELECT * FROM `enterprise_url_rewrite` WHERE `request_path` = @lookingFor AND `store_id` = @storeId;
SELECT * FROM `enterprise_url_rewrite_redirect` WHERE `identifier` = @lookingFor AND `store_id` = @storeId;
SELECT * FROM `cms_page` INNER JOIN `cms_page_store` ON `cms_page_store`.`page_id` = `cms_page`.`page_id` AND `cms_page_store`.`store_id` = @storeId WHERE `cms_page`.`identifier` = @lookingFor;
```

0 results

**Comment by craigcarnell** [comment] 2017-01-11 16:10
```
SET @storeId = 22;
SET @lookingFor = 'upright-vacuum-cleaners/swift-upright-22';

SELECT * FROM `enterprise_url_rewrite` WHERE `request_path` = @lookingFor AND `store_id` = @storeId;
SELECT * FROM `enterprise_url_rewrite_redirect` WHERE `identifier` = @lookingFor AND `store_id` = @storeId;
SELECT * FROM `cms_page` INNER JOIN `cms_page_store` ON `cms_page_store`.`page_id` = `cms_page`.`page_id` AND `cms_page_store`.`store_id` = @storeId WHERE `cms_page`.`identifier` = @lookingFor;
```

0 results for all 3

```
SET @storeId = 22;
SET @lookingFor = 'upright-vacuum-cleaners/swift-upright';

SELECT * FROM `enterprise_url_rewrite` WHERE `request_path` = @lookingFor AND `store_id` = @storeId;
SELECT * FROM `enterprise_url_rewrite_redirect` WHERE `identifier` = @lookingFor AND `store_id` = @storeId;
SELECT * FROM `cms_page` INNER JOIN `cms_page_store` ON `cms_page_store`.`page_id` = `cms_page`.`page_id` AND `cms_page_store`.`store_id` = @storeId WHERE `cms_page`.`identifier` = @lookingFor;
```

1 result - 29552105	upright-vacuum-cleaners/swift-upright	catalog/category/view/id/54	1	b073e9f4cecb21c25eed83a749696432	upright-vacuum-cleaners/swift-upright	1	50	22	2
0 results
0 results

**Comment by dfelton** [comment] 2017-01-11 16:12
@craigcarnell Sorry I'm gonna need more coffee this morning before I can wrap my head around some of this.

I'm not entirely positive... but I think it very well may be from the `enterprise_url_rewrite` table then that a duplicate is being created for some reason. Despite only 1 record in there, I think the migration tool is creating a **rewrite** for a product as well as a **redirect** for that very same product?

How concerned are you about your old redirects? If you are willing to scrap them and start your Magento 2 site simply with working category, product, and page URLs then you could probably comment out [this line](https://github.com/magento/data-migration-tool/blob/master/src/Migration/Step/UrlRewrite/Version11300to2000.php#L653) the tool will **only** create the necessary rewrites to have your basic entities function properly.

Any lost redirects could be turned setup manually post-migration. Sorry for kinda throwing in the towel on that... been a long week over here already. 

Oh something important to note though, is it really looks like you have `auto_resolve_urlrewrite_duplicates` turned on. I can see that from the output of your Migration tool. I'd turn that off if you're looking to handle these manually which it seems you have been.

**Comment by craigcarnell** [comment] 2017-01-11 16:36
@dfelton As far as I can see

There is sub-category called swift-upright in 2 differnet stores (22 and 4)

There is a product with a url key of swift-upright (store 0)

I tried setting auto_resolve_urlrewrite_duplicates to 0 and that made no difference

**Comment by dfelton** [comment] 2017-01-11 16:45
@craigcarnell aha!!

It appears you have both a category, and product, with the same url_key. 

Inside your "upright-vacuum-cleaners" category, you have a product (id 247) with the URL key "swift-upright", AND inside the category "upright-vacuum-cleaners" you have a sub-category with the URL key "swift-cleaners".

**Comment by dfelton** [comment] 2017-01-11 16:47
oh lol looks like you just said the same thing. 

Yeah you'll need to determine what's more important here. You can't have both this sub-category, and this product, use the same URL. Changing the URL key for the subcategory to something slightly different such as "swift-uprights" would fix your issue.

**Comment by craigcarnell** [comment] 2017-01-11 17:07
@dfelton 👍 I'm going to re-run based on this tomorrow morning. I'll rename the category.

**Comment by craigcarnell** [comment] 2017-01-12 13:51
@dfelton After fixing the issue with categories/products having the same url-key (I had about 6 or 7) and using your code, I was able to convert the DB. Thank you very much for your help 👍
