### ISSUE TITLE
#Bug? - migrate:settings doesn't preserve special characters

### ISSUE THREAD

**Issue by MagePsycho** [magento/data-migration-tool#111] opened 2016-07-11 10:54 UTC
I am in the process of data migration from Magento EE 1.14.2.0 to Magento EE 2.1.0.
Running the command `php bin/magento migrate:settings {path/to/data-migration/config.xml}` migrates the settings and store data but the values with special characters are replaced by ???.

From where it handles the UTF-8 thing?

**Comment by victor-v-rad** [comment] 2016-07-11 11:07
Hi @MagePsycho 

Try this patch https://github.com/magento/data-migration-tool/pull/28

**Comment by victor-v-rad** [comment] 2016-07-11 11:16
It is not really clear what you are trying to migrate settings or data. But settings should go first anyway. Data is the second step.

**Comment by MagePsycho** [comment] 2016-07-11 11:19
Thanks for the link to the #patch.
Yeah I am running the migrate:settings in the first step (edited now).
BTW, I have one query: Do the data-migration-tool only operates on data? or it's also responsible for creating non-existing tables or fields?

**Comment by ilol** [comment] 2016-07-11 11:32
with data only. You have to create needed data table and fields before. MT provides the information for this .

**Comment by victor-v-rad** [comment] 2016-07-11 11:43
> it's also responsible for creating non-existing tables or fields?

It creates m2_cl_* tables and trg_* triggers  in your Magento 1 DB. Also temporary url_rewrite_m2*  table is created because you have EE

**Comment by victor-v-rad** [comment] 2016-07-11 11:46
An internal issue MAGETWO-54492 regarding to special characters was created

**Comment by MagePsycho** [comment] 2016-07-11 11:47
Perfect.

BTW, the patch for UTF-8 didn't work for me. Not sure what I have to reload after the change. I tried to run the command with option `--reset`
Is there anything specific that we have to do to reflect the changes in the data-migration-tool?

**Comment by victor-v-rad** [comment] 2016-07-11 11:59
You could share the DB dump of the particular table where you get ??? after migration. We will try to migrate it. You can send it through the email (find it in my profile https://github.com/victor-v-rad)

**Comment by MagePsycho** [comment] 2016-07-11 12:05
@victor-v-rad it's the `core_config_data` table.
Not sure what am I missing.

**Comment by victor-v-rad** [comment] 2016-07-11 12:10
What is the Collation / Character Set in your DB of M1 and M2?

**Comment by MagePsycho** [comment] 2016-07-11 12:20
> M1	utf8	utf8_general_ci
> M2	latin1	latin1_swedish_ci

**Comment by victor-v-rad** [comment] 2016-07-11 12:51
Have you tried to make your M2 utf8 utf8_general_ci also?

**Comment by MagePsycho** [comment] 2016-07-11 13:04
Yeah I run the `ALTER DATABASE M2 CHARACTER SET utf8 COLLATE utf8_general_ci;`
But nothing is helping me, getting lost.

**Comment by MagePsycho** [comment] 2016-07-12 10:06
@victor-v-rad This issue has been fixed.
In fact I was using wrong array:
File: vendor/magento/data-migration-tool/src/Migration/ResourceModel/Destination.php > getResourceConfig()
`$config['initStatements'] = $destination[$destinationType]['initStatements'];`
which should be
`$config['database']['initStatements'] = $destination[$destinationType]['initStatements'];`

And similar change for `vendor/magento/data-migration-tool/src/Migration/ResourceModel/Destination.php`

**Comment by victor-v-rad** [comment] 2016-07-12 10:27
Glad to hear that! So the fix https://github.com/magento/data-migration-tool/pull/28 works after your change
$config['database']['initStatements'] = $destination[$destinationType]['initStatements'];
?

**Comment by MagePsycho** [comment] 2016-07-12 11:02
Yes. that fixed it.
But not all rows were transferred from M1 to M2 (context: core_config_data).
Noticeable, base urls were not transferred. unable to login to M2 (Fix: update cookie settings), frontend showing design exception etc.
My Question here is: what kind of data are not transferred from M1 to M2 during `migrate:settings` ?
Thanks again for your help.

**Comment by victor-v-rad** [comment] 2016-07-12 11:05
See etc/ce-to-ce/settings.xml.dist for details

**Comment by MagePsycho** [comment] 2016-07-12 11:07
gotcha! Thanks a lot :)

**Comment by victor-v-rad** [comment] 2016-07-12 12:47
both cases are possible. But renaming it is recommendation

**Comment by victor-v-rad** [comment] 2016-09-14 07:08
The issue is a duplicate and will be fixed in #96

**Closed by victor-v-rad** 2016-09-14 07:08 UTC
