### ISSUE TITLE
Undefined offset: 9 in /vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 433

### ISSUE THREAD

**Issue by quienti** [magento/data-migration-tool#112] opened 2016-07-11 13:15 UTC
Magento 1 => 1.9.2.2
Magento 2 => 2.1.0
Data Migration Tool => 2.1.0

![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/16731776/2e3ad13a-477a-11e6-958b-e5ee368b31d0.jpg)

After try reset : 
![sans titre 2](https://cloud.githubusercontent.com/assets/7326954/16732024/6dc4bebe-477b-11e6-81e7-009f4df999f8.jpg)

**Comment by victor-v-rad** [comment] 2016-07-11 15:05
Hi @quienti 
It is hard to figure out what wrong with your eav_attribute_group and eav_entity_attribute. 
You could share your DB dump of the next Magento 1 tables:
eav_attribute_group
eav_attribute_set
eav_attribute
eav_entity_attribute
catalog_eav_attribute
customer_eav_attribute
eav_entity_type
You can send it through the email (find it in my profile https://github.com/victor-v-rad)
We will try to migrate it.

**Comment by quienti** [comment] 2016-07-11 15:15
Mail sent and thank you for your response

**Comment by ilol** [comment] 2016-07-12 08:04
@quienti, can you please close the issue?

**Comment by victor-v-rad** [comment] 2016-07-12 08:17
internal issue MAGETWO-55303 was created

**Comment by trungnguyenbss** [comment] 2016-07-18 09:29
i'm facing the same problem. Can you post what caused this issue and how to fix? Thanks alot!

**Comment by victor-v-rad** [comment] 2016-07-18 12:08
We are working on this issue. Most probably you have different eav_entity_type.entity_type_id in your Magento 1 and Magento 2

**Comment by andreymoskvenkov** [comment] 2016-07-26 18:55
Ha Ha! I am getting the same error, when migrating from CE 1.9.2.1 to EE 2.1.
But I am getting an error as "undefined offset 13". 13 - it is a "Default" attribute set ID of "order_item" entity type. It falls, when is trying to move "price" attribute to "product-details" group. However  "order_item"  entity type attributes are not assigned to any attribute group. I think the fix is: do not move such attributes into "product-details" group. Just to change the condition to:
`         if ($attributes[$attributeId]['attribute_code'] == $attributeCode &&
                isset($attributeSetGroups[$record->getValue('attribute_set_id')][$attributeGroupCode])
            ) {
                $record->setValue(
                    'attribute_group_id',
                    $attributeSetGroups[$record->getValue('attribute_set_id')][$attributeGroupCode]
                );
            }`

**Comment by andreymoskvenkov** [comment] 2016-07-26 19:04
Sh****. Now I get
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9' for key 'PRIMARY'

**Comment by theycallmepepper** [comment] 2016-07-26 19:26
I just ran into this one as well. (1.8.0.1 -> 2.1.0)  @andreymoskvenkov  The first answer gives a little more context on the second error you received: http://magento.stackexchange.com/questions/92578/data-migration-eav-step-error

I don't have a solid solution at the moment.

**Comment by andreymoskvenkov** [comment] 2016-07-26 19:38
I think the issue appears, when we have a project, which was initially implemented on some older Magento version and then upgraded many times to the latest version. I have another project on my local, which is on CE 1.9.2.1 as well, but I don't see attributes for "order", "order_item", "invoice", etc entity types in the "eav_attribute" table. Therefore for now I think the solution for me would be: just to delete all attributes from  "eav_attribute" table, where entity_type_id > 4. However need to keep in mind that there may be attributes for some custom entity types, which probably should not be deleted. However in my case there I have only Magento entity types.

**Comment by andreymoskvenkov** [comment] 2016-07-26 20:17
Yeah, now I am getting an error related to older backend types:
[ERROR]: Class catalog/product_attribute_backend_finishdate does not exist but mentioned in: eav_attribute.backend_model for attribute_id=63

**Comment by victor-v-rad** [comment] 2016-07-27 08:33
@quienti in your DB the field eav_attribute_group.attribute_group_name has French names. Rename it back to English and try migration again

**Comment by quienti** [comment] 2016-07-27 08:42
I can not try a new migration this week, but as soon as I have a few minutes, I try!
Thanks

**Comment by andreymoskvenkov** [comment] 2016-07-27 09:36
Btw, SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9' for key 'PRIMARY' 
error is thrown, when a rollback is being run. So, rollback does not work in case, when some error occursю

**Comment by andreymoskvenkov** [comment] 2016-07-27 13:11
Sorry, no, rollback does not work anyway, but this issue Duplicate entry '9' for key 'PRIMARY' is thrown, when Migration tool tries to insert not existing in CE edition entity type "rma_item". This entity type's ID is hardcoded in the Migration tool's helper as "9". Therefore if your eav_entity_type table contains more than 8 "standard" entity types (standard entity types are: 
catalog_category  
catalog_product   
creditmemo        
customer          
customer_address  
invoice        
order        
shipment
)
then the tool throws an exception, that "Duplicate entry '9'". In our table we have a lot of old entity types, such as "order_item", "invoice_item", etc + we have a custom entity type: "m_filter" from ManaDev extension. Therefore the migration tool would always throw an exception in my case. I have resolved it by deleting all entity types, except entity types from the list above.

**Comment by victor-v-rad** [comment] 2016-07-27 14:31
> This entity type's ID is hardcoded in the Migration tool's helper as "9"
internal ticket MAGETWO-55399 was created

**Comment by MagentoTest1111** [comment] 2016-08-10 07:22
@victor-v-rad i have changed my file like internal issue MAGETWO-55303 but again getting  same error

**Comment by victor-v-rad** [comment] 2016-08-15 10:00
@MagentoTest1111 2.1.1 release is not ready yet. It might be better to wait for a while

**Comment by baltechies** [comment] 2016-08-21 11:43
Hi, 
I have same issue.
Notice: Undefined offset: 1 in {PROJECT_PATH}/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 433 

Magento 1 => 1.9.2.2
Magento 2 => 2.1.0
Data Migration Tool => 2.1.0

**Comment by rtowings** [comment] 2016-08-22 14:57
Hi @baltechies,
Undefined offset 1 in Data.php line 433 is usually a secondary error.
Please empty your Magento2 database, Migrate settings. Then Migrate data using the -vvv flag and post:
1. your error
2. the first two lines of the stack trace.

**Comment by baltechies** [comment] 2016-08-22 15:47
Hi @rtowings ,
I have tried it many time and now did it again but same error.
**1) Error**
[Exception]                                                                                                                              
  Notice: Undefined offset: 1 in /Users/balvinderSingh/Sites/comitstore-mg2/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Dat  
  a.php on line 433 

**2) First two lines**
Exception trace:
 () at /Users/balvinderSingh/Sites/comitstore-mg2/vendor/magento/framework/App/ErrorHandler.php:61
 Magento\Framework\App\ErrorHandler->handler() at /Users/balvinderSingh/Sites/comitstore-mg2/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:433
 Migration\Step\Eav\Data->moveAttributeToGroup() at /Users/balvinderSingh/Sites/comitstore-mg2/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php:400


I have attached the screenshot of terminal.
![screen shot 2016-08-22 at 9 08 41 pm](https://cloud.githubusercontent.com/assets/13519944/17861110/6cba0d3c-68ad-11e6-86d1-3eea66c7dafc.png)

**Comment by rtowings** [comment] 2016-08-22 16:25
Hi @baltechies,

Just to be clear.  Did you begin your latest attempt with an empty Magento2 database?

**Comment by baltechies** [comment] 2016-08-22 16:30
Yes. I did it with empty Magento2 Database. I have the backup of magento2 database after fresh installation.

**Comment by rtowings** [comment] 2016-08-22 16:33
OK, try running the following query.

select distinct attribute_set_id from eav_attribute_group where attribute_set_id > 8 and attribute_set_id not in (select attribute_set_id from eav_attribute_set where entity_type_id = 4);

**Comment by baltechies** [comment] 2016-08-22 16:38
I run this query on current magento2 database and its return 38 rows.
I run this query on magent1 databse as well and its return 31 rows.

**Comment by baltechies** [comment] 2016-08-22 16:57
@rtowings Is there any clue? What should I do further?

**Comment by rtowings** [comment] 2016-08-22 17:08
What's going on is that your Magento1 database has some missing data (or extra data, depending on your perspective).  Basically, in M1 attributes are grouped into sets in the tables eav_attribute_group and eav_attribute_set.  The query you ran on your M1 database returned the attribute_set_id numbers that exist in eav_attribute_group and should (but don't) exist in eav_attribute_set.  This is likely due to a bug in an earlier Magento release that deleted the attribute_groups, but did not delete the corresponding sets.

You have 3 choices:
1) add the missing records to eav_attribute_set in your M1 database.
2) delete the extra records from eav_attribute_group in your M1 database - I dislike this option, because there is risk in destroying data, but it should work. (make sure you backup first!)
3) wait for an update in the migration tool that might look for this issue and take appropriate action.

I'll message you separately with some instructions.

**Comment by baltechies** [comment] 2016-08-22 17:34
@rtowings  Thank you. I will look into database and update you. I have checked database roughly and found that eav_attribute_set table has entry which is not exist in eav_attribute_group table.

**Comment by baltechies** [comment] 2016-08-22 17:59
@rtowings All attribute_set_id numbers that exist in eav_attribute_group are also exist in eav_attribute_set. I am not capturing what is going wrong here.

**Comment by rtowings** [comment] 2016-08-22 18:03
@baltechies  the larger issue would be the missing entries in eav_attribute_set 

MAKE SURE YOU BACK UP YOUR M1 database.  Or better yet, copy the full database and make changes to the copy.  Then run your migration from the copy.

Take the set_ids returned from this query on your M1 database:
select distinct attribute_set_id from eav_attribute_group where attribute_set_id > 8 and attribute_set_id not in (select attribute_set_id from eav_attribute_set where entity_type_id = 4);

and extend the following query to include each of the missing set_ids:
INSERT INTO  eav_attribute_set  VALUES (1st_set_id_returned,4,'Missing1',0), (2nd_set_id_returned,4,'Missing2',0),(3rd_set_id_returned,4,'Missing3',0);

Note that the 'Missing1', etc must be unique, which is why it increments with each record.

I'm still concerned, though, that you have issues with your empty M2 database.  The error you received would suggest that your M1 database is missing a core record in eav_attribute_set, which is unlikely.  My recommendation would be to reinstall Magento 2 and work from the resulting empty db.

**Comment by rtowings** [comment] 2016-08-22 18:52
Hi @baltechies.  

The query I had you run earlier on your M1 database [[select distinct attribute_set_id from eav_attribute_group where attribute_set_id > 8 and attribute_set_id not in (select attribute_set_id from eav_attribute_set where entity_type_id = 4);]] returns a list of attribute_set_id that DO exist in eav_attribute_group, but DO NOT exist in eav_attribute_set FOR THE ERROR YOUR REPORTED.

If the sets DO exist in eav_attribute_set, then they exist for a different entity than would be at issue for the error you reported.

Again, I am suspicious that there are issues with your empty M2 database.  Please re-run your install and attempt the migration again into the newly created, empty M2 database.  Please remember to use the -vvv flag.

**Comment by baltechies** [comment] 2016-08-23 15:32
Hi @rtowings 
I have installed fresh copy of magento 2.1 and run migration on this. But same issue nothing change.

I have run "select distinct attribute_set_id from eav_attribute_group where attribute_set_id > 8 and attribute_set_id not in (select attribute_set_id from eav_attribute_set);" and its return 0 rows.

**Comment by victor-v-rad** [comment] 2016-08-25 08:38
Please check that in your DB the field eav_attribute_group.attribute_group_name in English.

**Comment by baltechies** [comment] 2016-08-25 08:52
@victor-v-rad  There are 127 rows. What should I check?

**Comment by baltechies** [comment] 2016-08-30 10:05
@victor-v-rad  Its seems that there is an issue in data migration tool version 2.1.
I installed a fresh copy of magento 2.0.7 and data migration tool version 2.0.7. Then I am able to migrate magento1 database into magento2. 
Now I am facing is a new issue, I am unable to edit and add new product, Its showing empty screen.
Can you please suggest related to this?
![screen shot 2016-08-30 at 3 31 03 pm](https://cloud.githubusercontent.com/assets/13519944/18085059/25d5df0c-6ec7-11e6-92f8-d53f19811f36.png)

**Comment by victor-v-rad** [comment] 2016-09-05 10:29
@quienti 
The issue was fixed in the latest release of the tool 2.1.1
Please recheck

**Comment by quienti** [comment] 2016-09-05 11:12
@victor-v-rad Thank you, I will check in a few days

**Comment by baltechies** [comment] 2016-09-06 05:53
@victor-v-red
I am able to migrate data from magento 1 to magento 2.1 with data migration tool 2.1.1.
But I faced some issues, Like 
1) products and categories are not shown on frontend.
2) In admin panel, category (Product-> categories) thowing exception error. Error is
a:4:{i:0;s:139:"Notice: Undefined offset: 564 in [Magento_PATH]/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166";i:1;s:6828:"#0

**Comment by victor-v-rad** [comment] 2016-09-07 10:15
@baltechies 
Not able to identify the cause. You could send your DB dump (remove all passwords in it before). See my email in my profile https://github.com/victor-v-rad 
I would try to migrate and test

**Comment by victor-v-rad** [comment] 2016-09-07 13:15
Thank you @baltechies  for the DB you sent 
Migrated successfully and the issues you described are exist. In order to solve it I need new issue in github please make it and Copy/Past your last comment

**Comment by baltechies** [comment] 2016-09-07 16:23
@victor-v-rad
I have created a new issue [#153](https://github.com/magento/data-migration-tool/issues/153)

**Comment by victor-v-rad** [comment] 2016-09-14 07:12
It seems the initial issue is fixed and I close it. Feel free to reopen if it is still actual

**Closed by victor-v-rad** 2016-09-14 07:12 UTC

**Comment by quienti** [comment] 2016-09-14 13:54
Just for information, my migration work correctly

Thanks

**Comment by ilol** [comment] 2016-09-14 14:02
Great!

**Comment by techverx** [comment] 2016-09-30 16:48
Hi guyz, I migrated data from magento 1.9.2.4 to magento 2.1.1 and successfully completed all steps. Everything looks good and all data imported but when i go to Products->categories i am seeing this error.

Notice: Undefined offset: 31 in /var/www/coral/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166

Help much appreciated. :)

**Comment by victor-v-rad** [comment] 2016-10-03 06:46
It is hard to figure out what is wrong in your case
You could share DB dump (remove all passwords before) of Magento 1 and send it through email (find it in my profile https://github.com/victor-v-rad)
We will try to migrate it to reproduce and fix

**Comment by myselfgaurav** [comment] 2016-10-17 22:33
I am stuck since 3 days trying to migrate my magento 1 to magento 2.
I keep on getting below error:

**[PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '136' for key 'PRIMARY'**

i did reset and did reset multiple times still no success , how can i find which database has duplicate value , please help me to fix i have attached my magento 1 database also .(to you in seperate mail)

**Comment by lano-vargas** [comment] 2017-02-20 09:56
I am also having issue with migrating from 1.9.2.1 to 2.1.0.

In the first run I get [Exception]                                                                                                                                          
  Notice: Undefined offset: 1 in ../../../magento2/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 209
Second run I get [PDOException]                                                                                                                                             
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-Migration_Default' for key 'EAV_ATTRIBUTE_SET_ENTITY_TYPE_ID_ATTRIBUTE_SET_NAME'

I am not sure how to fix pass this issue, has anyone got a solution please share. thank's.

**Comment by PradeepAvion** [comment] 2017-05-17 07:23
[Exception]                                                                                                                                  
  Notice: Undefined offset: 19 in /home/bestalzheimers/public_html/newbestalzheimers/vendor/magento/data-migration-tool/src/Migration/Step/Ea  
  v/Data.php on line 249 

Magento 1 => 1.9.1.0
Magento 2 => 2.1.2
Data Migration Tool => 2.1.2

![screenshot from 2017-05-17 12 52 44](https://cloud.githubusercontent.com/assets/28750270/26142787/c3f8e896-3aff-11e7-9f38-72cbdee802c0.png)

**Comment by natsoGR** [comment] 2017-06-21 21:37
i am trying to migrate 1.7.0.2 to 2.1.7
`[Exception]
Notice: Undefined offset: 19 in /home/m2/public_html/vendor/magento/data-migration-tool/src/Migration/Step/Eav/Data.php on line 278`

I don't know how to fix it

<img width="1137" alt="screen shot 2017-06-22 at 00 34 08" src="https://user-images.githubusercontent.com/22493050/27407866-cc10e188-56e2-11e7-8991-23bc456d4e42.png">

**Comment by manojroka** [comment] 2017-07-17 13:10
@natsoGR did you find any fix for it? I am getting the exactly same error.

**Comment by natsoGR** [comment] 2017-07-17 13:14
@manojroka unfortunately no.

**Comment by manojroka** [comment] 2017-07-18 11:57
@natsoGR I restarted the migration process with fresh install and correct ignore documents list, It is now completed without any errors [migration 1.7.0.2 to 2.1.7].

**Comment by patadeloso** [comment] 2017-09-14 19:58
Has anyone nailed down a solution for this? Seen this happen on 1.7.x=>2.1.7 and 1.9.x=>2.1.7.

**Comment by wajahatbashir** [comment] 2018-04-03 08:45
Hi Guys, I migrated data from magento 1.9.2 to magento 2.1.2 and successfully Category step. Everything looks good and all data imported but when i go to Products->categories i am facing this error.

Notice: Undefined offset: 31 in /var/www/coral/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166

How to i can fix this issue.
