### ISSUE TITLE
Magento 1.9.3.6 To Magento 2.2.0

### ISSUE THREAD

**Issue by AbdulKadir-Agoliya** [magento/data-migration-tool#384] opened 2017-10-07 10:35 UTC
I have installed fresh Magento 2.2.0 and restarted migration 
Magento1 is multistore 

php version 7.1.10

I Have set bulk_size ,direct_document_copy  too

php bin/magento migrate:data -r /public_html/magento2/vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.9.3.6/config.xml

Its give me errror 
Notice: Array to string conversion in /public_html/magento2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php on line 169

statement on line 169   $statement->execute($bind);

Is Anyone Have Idea?

**Comment by victor-v-rad** [comment] 2017-10-09 08:53
The problem is I cannot reproduce it in my environment. Have you tried PHP 7.0?

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-09 10:29
no i am using PHP 7.1.10

**Comment by victor-v-rad** [comment] 2017-10-09 11:25
@AbdulKadir-Agoliya 

I can suggest sending me DB dump (if it is not too big) or give a link. I will migrate to find the issues you faced

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-09 12:19
i have  sent you a link in mail

**Comment by victor-v-rad** [comment] 2017-10-09 13:34
> Its give me errror
Notice: Array to string conversion in /public_html/magento2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php on line 169

I have migrated your DB and found no issue found that you described. 

I used 
```
<direct_document_copy>0</direct_document_copy>
<bulk_size>0</bulk_size>
```
and
```
<direct_document_copy>1</direct_document_copy>
<bulk_size>500</bulk_size>
```
both works in my environment. My PHP 7.0.19. I will try using  PHP 7.1

**Comment by victor-v-rad** [comment] 2017-10-10 08:23
Tried on PHP 7.1 Found only
```
  [Exception]
  Notice: A non well formed numeric value encountered in C:\Dev\workspace\data-migration-tool\src\Migration\ResourceModel\AbstractResource.php on line 231
```

Did not catch your error 
```
Notice: Array to string conversion in /public_html/magento2/vendor/magento/data-migration-tool/src/Migration/ResourceModel/Adapter/Mysql.php on line 169
```
 unfortunately

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-10 09:15
I solved that error using 

A non well formed numeric value encountered.

https://github.com/magento/data-migration-tool/pull/267/commits/e1963d7c7159719d7def5f92d1e1f9c586da508e

**Comment by victor-v-rad** [comment] 2017-10-10 09:39
Great!

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-10 11:31
did You Find Any Solution on PHP7.1?

**Comment by victor-v-rad** [comment] 2017-10-10 12:03
@AbdulKadir-Agoliya  
this https://github.com/magento-panda/data-migration-tool/commit/5fc6ff3c5c89aea88e8843c55fdafc9cf3bd6f3b should help

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-10 12:40
i have checked it after setting memory limit 1024 static but it didnt work

**Comment by victor-v-rad** [comment] 2017-10-10 13:26
@nimeshdolphin 

I can suggest sending me DB dump (if it is not too big) or give a link (find my email in [my profile](https://github.com/victor-v-rad)). I will migrate to find the issue you faced

**Comment by nimeshdolphin** [comment] 2017-10-10 14:15
After debugging, I found there is an issue in "sales_flat_order_item" table's "product_options" column.
Which stores serialized data and while migrating, it's converted to JSON.

I've updated the value of this column to NULL for all the rows, and Migration completed successfully.

So, issue is in this column while converting serialized data to JSON.

Can you please check it ?

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-11 04:35
#victor-v-rad Thank you so much for your Help

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-11 04:42
But i want to reason why its happen and how i can i solve that error.It may be possible that same error will arise in feature so we have to know solution.

**Comment by victor-v-rad** [comment] 2017-10-11 05:07
@nimeshdolphin 
Could you provide some example of value of sales_flat_order_item.product_options which causes `Notice: Array to string conversion in` ?
As you can see in \Migration\Handler\SerializeToJson\SalesOrderItem::handle() there are cases when double unserialize happens (for option_type === file and bundle_selection_attributes) So I assume there could be more such cases when data is not unserialized

**Comment by nimeshdolphin** [comment] 2017-10-11 05:43
@victor-v-rad I've mailed sales_flat_order_item table for testing it's product_options column.
Can you please test with this exact PHP versions ?  7.0.23 and 7.1.9.

**Comment by victor-v-rad** [comment] 2017-10-11 09:43
@nimeshdolphin @AbdulKadir-Agoliya 
Here is the fix for `Notice: Array to string conversion` https://github.com/magento-panda/data-migration-tool/commit/1d3226c833be529c288ffa951658577669855541
It will be included into next release by default

**Comment by AbdulKadir-Agoliya** [comment] 2017-10-11 10:30
Thank You So Much @victor-v-rad

**Closed** 2017-11-10 06:02 UTC
