### ISSUE TITLE
How to ignore EAV attributes?

### ISSUE THREAD

**Issue by MagePsycho** [magento/data-migration-tool#115] opened 2016-07-14 12:12 UTC
I didn't find any mapping file where I can ignore the cusotm eav attributes for products.
Please do suggest.

**Comment by redboxmarcins** [comment] 2016-07-14 14:19
Ideally - delete them from source data - so you are only migrating what required

**Comment by MagePsycho** [comment] 2016-07-14 14:32
But that's not the correct way. I was thinking if ignoring attributes can be done based on mapping files just like tables and fields.

**Comment by victor-v-rad** [comment] 2016-07-14 14:37
Use eav-attribute-groups.xml.dist for this

**Comment by MagePsycho** [comment] 2016-07-14 14:39
WOW that's cool.
BTW, is there's a way to know which tables has been imported so far? 
My Map Step is stuck at 12%, and not sure which tables' data are being updated.

**Comment by victor-v-rad** [comment] 2016-07-15 03:39
use -vvv option. It shows progress bar per table and code backtrace of an error if any

**Comment by MagePsycho** [comment] 2016-08-11 13:54
Is there a way to ignore attribute by entity_type? I want to ignore product > `custom_image` but not category > `custom_image`?

If you add `custom_image` attribute in `eav-attribute-groups.xml`, it will ignore for all, right?

**Comment by victor-v-rad** [comment] 2016-08-12 13:25
>Is there a way to ignore attribute by entity_type?

Not implemented yet. Internal ticket MAGETWO-56809

**Comment by victor-v-rad** [comment] 2016-09-14 07:17
The issue is a duplicate of #134 follow up for it.

**Comment by victor-v-rad** [comment] 2016-10-19 09:07
The bug was fixed in the recent release. Please try it out. Feel free to reopen the issue if it is still relevant.

**Closed** 2016-11-03 10:49 UTC
Labels: acknowledged, bug

**Comment by carloshernan007** [comment] 2017-02-27 14:48
Hi, I try of ignore the attributes of customer for example cedula my code is 

`<attribute type="customer">cedula</attribute>`

Document: eav_attribute_group. Fields: attribute_group_code,tab_group_code
[2017-02-27 14:32:53][ERROR]: Source fields are not mapped. Document: catalog_eav_attribute. Fields: is_required_in_admin_store,is_used_in_grid,is_visible_in_grid,is_filterable_in_grid,search_weight,additional_data

**Comment by danielruedaa** [comment] 2017-03-24 15:48
To ignore client attributes uses the file eav-attribute-groups.xml.dist and create a copy

`cp eav-attribute-groups.xml.dist eav-attribute-groups.xml`

In the node ignore we placed the attributes that we want to be careful with the type of attribute that we place example

` <groups xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../groups.xsd">
<group name="ignore">
   <attribute type="catalog_product">msrp_enabled</attribute>
     
   <attribute type="customer">cedula</attribute>
    
</group>
</groups>`

If the type is the indicated ignore the one you want, otherwise it will not do anything or ignore it in another place With the edited document we go to do the migration
